assets:
  config.yml: zerocracy/home#assets/threecopies/config.yml
  id_rsa: zerocracy/home#assets/heroku-key
  id_rsa.pub: zerocracy/home#assets/heroku-key.pub
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    bundle install
    rake
    cp ../config.yml config.yml
    git remote add heroku git@heroku.com:threecopies.git
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git add config.yml
    sed -i -s 's|Gemfile.lock||g' .gitignore
    git add Gemfile.lock
    git add .gitignore
    git commit -m 'config.yml & others'
    git fetch
    sed -i "s/BUILD/${tag}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.threecopies.io > /dev/null
  commanders:
  - yegor256
architect:
- yegor256
merge:
  commanders: []
  script: |-
    bundle install
    rake
deploy: {}
